FROM node:20 as builder
WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build
FROM nginx as production
COPY --from=builder /app/dist/front-end /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]